language: python

sudo: false

env:
  - TOXENV=flake8
  - TOXENV=isort
  - TOXENV=py27
  - TOXENV=py33
  - TOXENV=py34

matrix:
  include:
    - python: 3.5
      env:
      - TOXENV=py35

install:
  - pip install tox flake8 pep8-naming isort codecov

script:
  - tox

after_success:
  - codecov -e TOXENV
